// LOCAL HOST DEV
### Get all books
GET http://localhost:3000/favorites
### Post book listing
POST http://localhost:3000/favorites HTTP/1.1
content-type: application/json

{
    "title": "A Testing Book",
    "authors": ["Alyssa Lahoy", "Test Testerson"],
    "publishing": "10/22/2022",
    "language": "English",
    "genres": ["novel", "fiction", "tragedy", "drama"]
}

### Update a book listing entirely
PUT http://localhost:3000/favorites/6354b9b9f674abba111e8246 HTTP/1.1
content-type: application/json

{
    "title": "Update: A Test",
    "authors": ["Alyssa Lahoy", "Test Testerson", "Checkster Test"],
    "publishing": "10/21/2022",
    "language": "English",
    "genres": ["fiction", "tragedy", "drama"]
}

### Update a book listing title
PUT http://localhost:3000/favorites/update-title/6354b9b9f674abba111e8246 HTTP/1.1
content-type: application/json

{
    "title": "How to Update: Title Ver."
}

### Delete an entire book listing
DELETE http://localhost:3000/favorites/6354b9b9f674abba111e8246 HTTP/1.1



//Auth0 requests
### acquire code for authorization
GET https://dev-aw6dgqrx2oi2y5at.us.auth0.com/authorize?response_type=code&client_id=AFtv3dWiURIKQCNsvn17lMQ9t6hOsxkr&redirect_uri=http%3A%2F%2Flocalhost%3A3000%2Fcallback&state=1234&scope=openid%20profile%20email

### acquire tokem
POST https://dev-aw6dgqrx2oi2y5at.us.auth0.com/oauth/token?grant_type=authorization_code&client_id=AFtv3dWiURIKQCNsvn17lMQ9t6hOsxkr&client_secret=dcuddHo4o-405Emks0G_8XkvK1BEBgjOIeC4yYLiGp8fPa8WD-bbOO---fSFzzIS&redirect_uri=http%3A%2F%2Flocalhost%3A3000%2Fcallback&scope=openid%20profile%20email&code=IkboZcZ6mArpHezKEjQAVSpitk1vIERA3XzDrNOXJc3BK


// PRODUCTION
###
GET https://cse341-library.onrender.com/favorites